apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: confluence-to-markdown
  title: Confluence to Markdown
  description: Converts a single Confluence doc to Markdown and adds it to a repo.
spec:
  owner: my-team@example.com
  type: service
  parameters:
    - title: Confluence and Github Repo Information
      properties:
        confluenceUrls:
          type: array
          description: URLs of Confluence docs
          items:
            type: string
          minItems: 1
          maxItems: 5
        repoUrl:
          type: string
          title: GitHub Repo for mkdocs.yml
  steps:
    - id: create-docs
      name: Get Markdown
      action: confluence:transform:markdown
      input:
        confluenceUrls: ${{ parameters.confluenceUrls }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: publish
      name: Publish PR to GitHub
      action: publish:github:pull-request
      input:
        repoUrl: <GITHUB_BASE_URL>
        branchName: confluence-to-markdown
        title: Confluence to Markdown
        description: PR for converting Confluence page to mkdocs
